name: Deploy Documentation to Github Pages

on:
  # Runs on pushes targeting default branch
  push:
    branches: ["main"]

  # Allows manual execution of workflow from github
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
        run: npm ci
        run: npx compodoc -p tsconfig.doc.json -d docs
