name: Deploy Documentation to Github Pages

on:
  # Runs on pushes targeting default branch
  push:
    branches: ["main"]

  # Allows manual execution of workflow from github
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, but don't cancel in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm ci
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - run: npx compodoc -p tsconfig.doc.json  # Compodoc create documentation/ folder
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4
